In [7]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [8]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [9]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()
def projected_salary(salary):
    return salary * 1.03

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [10]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg']* 1.03

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [11]:
type(df['job_skills'][0])

float

In [13]:
df['job_skills'].iloc[0]

nan

In [14]:
import ast

df['job_skills'] = df['job_skills'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else []
)

In [21]:
df['job_skills'].iloc[0]

[]

In [22]:
import ast
(df['job_skills'][0])

[]

In [25]:
def clean_list(skill_list):
    if isinstance(skill_list, list):
        return skill_list
    elif pd.isna(skill_list):
        return []
    else:
        return ast.literal_eval(skill_list)

df['job_skills'] = df['job_skills'].apply(clean_list)

In [28]:
type(df['job_skills'][0])

list

In [32]:
df['job_skills'] = df['job_skills'].apply(
    lambda skill_list: ast.literal_eval(skill_list)
    if isinstance(skill_list, str) and pd.notna(skill_list)
    else []
)

In [34]:
def clean_list(skill_list):
    if isinstance(skill_list, list):
        return skill_list
    elif pd.isna(skill_list):
        return []
    else:
        return ast.literal_eval(skill_list)

df['job_skills'] = df['job_skills'].apply(clean_list)

In [35]:
df['job_skills'][0]

[]